# Generated by Django 2.2.4 on 2019-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='importance',
            field=models.CharField(choices=[('C', 'Обычно'), ('B', 'Важно'), ('A', 'Срочно!')], max_length=1),
        ),
    ]
